query GetNowShowing($page: Int, $perPage: Int) {
    Page(page: $page, perPage: $perPage) {
        pageInfo {
            hasNextPage
            currentPage
            lastPage
        }
        media(type: ANIME, status: RELEASING, sort: [TRENDING_DESC]) {
            id
            title {
                romaji
                english
                userPreferred
            }
            coverImage {
                extraLarge
                large
                color
            }
            bannerImage
            genres
            averageScore
            popularity
            status
            seasonYear
            description
            trailer {
                id
                site
                thumbnail
            }
        }
    }
}